### ISSUE TITLE
⛔ Warning (emacs): Error loading "plantuml-mode" autoloads: (void-variable compilation-error-regexp-alist)

### ISSUE THREAD

**Issue by Ziqi-Yang** [xshyamx/simple-plantuml-mode#1]
When starting Emacs, there is an error:
```
⛔ Warning (emacs): Error loading "plantuml-mode" autoloads: (void-variable compilation-error-regexp-alist)
```
Here is my configuration:
```lisp
(use-package plantuml-mode
  :elpaca (:type git :host github :repo "xshyamx/simple-plantuml-mode"))
```

**Comment by xshyamx** [comment]
`compilation-error-regexp-alist` is defined in compile.el. Are you able to run ?

```emacs-lisp
(require 'compile)
```

**Comment by xshyamx** [comment]
The `autoload` for setting up the compilation error regexps was giving the warning when elpaca was byte compiling the file. 5a5401854d5c98b2531bc5a0257c31d35bd547bd fixes the issue

Thanks for reporting @Ziqi-Yang got to know about elpaca. Seems pretty cool :)
